config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :managers, :skip => [:sessions, :registrations, :unlocks]
  devise_scope :manager do
    get '/management/login' => 'devise/sessions#new', :as => :new_manager_session
    post '/management/login' => 'devise/sessions#create', :as => :manager_session
    delete 'management/logout' => 'devise/sessions#destroy', :as => :destroy_manager_session
  end

  resource :management, only: [:show] do
    authenticate :manager do
      mount Sidekiq::Web => '/sidekiq'
    end
    resources :users, only: [:index, :show, :update], controller: 'managements/users' do
      member do
        patch :lock
        patch :unlock
      end
    end
    resources :campaigns, only: [:index, :show, :update], controller: 'managements/campaigns'
    resources :reports, only: [:index], controller: 'managements/reports' do
      member do
        patch :check
        patch :uncheck
      end
    end
    resources :messages, only: [:index, :show, :destroy], controller: 'managements/messages'
    resources :product_types, only: [:index, :new, :create, :edit, :update, :destroy], controller: 'managements/product_types'
    resources :products, controller: 'managements/products' do
      resources :product_details, controller: 'managements/products/product_details', only: [:create, :edit, :update]
    end
  end
#============================ Dashboard ROUTES =======================#
  resource :dashboard, only: [:show] do
    resources :bundles, only: [:index], controller: 'dashboards/bundles' do
      resource :purchase, only: [:create, :show], controller: 'dashboards/bundles/purchases' do
        member do
          get :callback
        end
      end
    end
  end
#============================ USERS ROUTES ============================#
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :passwords, :registrations]
  devise_scope :user do
    get "/login" => "sessions#new", :as => :new_user_session
  end
  resource :session, only: [:show]
#============================ API ROUTES ===============================#
  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:index] do
        collection do
          get :self
        end
      end
      resources :sessions, only: [:create]
      resources :campaigns, only: [:index, :new, :create] do
        resource :like, only: [:create], controller: 'campaigns/likes'
        resource :report, only: [:create], controller: 'campaigns/reports'
        collection do
          get :next
        end
      end
      resources :products, only: [:index] do
        resource :purchase, only: [:create], controller: 'products/purchases'
      end
      resources :bundles, only: [:index]
      post 'bundles/:bazaar_sku/purchase' => 'bundles/purchases#create', as: :bundle_purchase
      resources :messages, only: [:create]
    end
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  include PublicActivity::Common
  attr_accessor :target_url, :payment_type, :waiting

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  belongs_to :owner, class_name: 'User'
  belongs_to :campaign_class
  has_many   :reports, dependent: :destroy
  has_many   :reporters, through: :reports, source: :user

  validates :budget, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :owner, presence: true
  validates :campaign_class, presence: true

  validate  { |campaign| CampaignValidator.new(campaign).validate }

  enum status: { pending: 'pending', available: 'available', rejected: 'rejected',
                 ended: 'ended', check_needed: 'check_needed' }

  # Based on the passed status returns the respective
  # scoped relation.
  def self.with_status(status)
    {
      available: self.available,
      finished: self.finished,
      pending: self.pending,
      rejected: self.rejected
    }.fetch(status.to_sym) { self }
  end

  # Creates a hash full of fields and their states
  # based on the waiting state.
  #
  # @return [Hash]
  def self.fields(waiting=nil)
    Hash.new.tap do |fields|
      fields[:description] = waiting ? true : false
      fields[:phone] = waiting ? true : false
      fields[:website] = waiting ? true : false
      fields[:address] = waiting ? true : false
    end
  end

  # Verifies a pending campaign and makes it available.
  def verify!
    available! if pending?
  end

  # Rejects a pending or currently available campaign.
  # Sets the status field to `rejected` and
  # returns the budget back to the owner's account.
  def reject!
    return unless pending? || available?
    begin
      # based on the campaign_type returns the budget back to the account
      ActiveRecord::Base.transaction do
        if payment_type == "coin"
          owner.coin_credit += budget
        else
          owner.like_credit += budget
        end
        rejected!
        owner.save!
      end
    rescue => e
      Rails.logger.error e
    end
  end

  # Returns available campaigns that are not liked by the user
  #
  # @return [Campaign] the next campaign
  def self.for_user(user)
    self.available.where("id not in (select campaign_id from likes where user_id = ? and status = 'available')", user.id).first
  end

  # Checks if user has already liked the campaign.
  #
  # @return [Boolean] true if user liked the campaign, false otherwise.
  def liked_by? user
    Like.exists?(campaign: self, user: user)
  end

  def payment_type
    @payment_type || campaign_class.payment_type
  end

  def campaign_type
    type.chomp("Campaign").underscore
  end

  def waiting
    return campaign_class.waiting if @waiting.nil?
    @waiting
  end

end

app/models/campaigns/instagram_campaign_service.rb
class InstagramCampaignService < Campaign

  has_attached_file :cover,
                    path: ":rails_root/public/system/:class/:attachment/:id_partition/:style/:filename",
                    styles: {
                              medium: "300x300>",
                               thumb: "100x100>"
                            }

  validates_attachment :cover,
                        content_type: { content_type: "image/jpeg" },
                        size: { in: 0..2.megabytes }

  def creation_validator
    InstagramPhotoValidator.new(self)
  end

  def liking_validator
    InstagramLikeValidator
  end

  # Sets a {CampaignClass} based on the request for waiting, campaign_type
  # and payment_type.
  def set_campaign_class!
    self.campaign_class = if waiting == true
                            CampaignClass.active.where(campaign_type: type,
                                                payment_type: payment_type)
                                         .where.not(waiting: 0).last
                          else
                            CampaignClass.active.where(campaign_type: type,
                                                payment_type: payment_type,
                                                waiting: 0).last
                          end
  end

  # Gets photo address from Instagram API and
  # calls {CampaignCoverDownloaderJob} job to fetch the cover
  def fetch_cover
    media = Instagram.client.media_shortcode(target)
    CampaignCoverDownloaderJob.set(wait: 10.second)
                              .perform_later self, media.images.standard_resolution.url
  end

  # Returns Instagram photo url based on the target
  #
  # @return [String] Instagram photo url.
  def target_url
    @target_url || "http://instagram.com/p/#{target}"
  end

end

app/models/campaigns/instagram_campaigns/instagram_liking_campaign.rb
class InstagramLikingCampaign < InstagramCampaignService

  validates :description, length: { maximum: 500 }, allow_blank: true
  validates :phone, length: { in: 10..12 }, allow_blank: true
  validates :website, length: { maximum: 150 }, allow_blank: true,
                      format: { with: /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\z/ }
  validates :address, length: { maximum: 200 }, allow_blank: true

end

app/controllers/api/v1/campaigns/likes_controller.rb
class Api::V1::Campaigns::LikesController < Api::V1::ApiController

  def create
    campaign = Campaign.find params[:campaign_id]
    result = LikeCampaign.new(campaign, current_user, like_params)
    if result.like!
      render json: current_user, serializer: Api::V1::UserSerializer, status: :created
    else
      if result.campaign.errors[:base].include?(t('errors.messages.access_token_invalid'))
        render json: { errors: result.campaign.errors }, status: :unauthorized
      else
        render json: { errors: result.campaign.errors }, status: :unprocessable_entity
      end
    end
  end

  private

  def like_params
    params.require(:like).permit(:access_token)
  end

end

app/controllers/api/v1/campaigns/reports_controller.rb
class Api::V1::Campaigns::ReportsController < Api::V1::ApiController

  def create
    campaign = Campaign.find params[:campaign_id]
    if Report.find_by(user: current_user, campaign: campaign).blank?
      campaign.reporters << current_user
      head :created
    else
      head :ok
    end
  end

end

app/controllers/api/v1/campaigns_controller.rb
class Api::V1::CampaignsController < Api::V1::ApiController

  def index
    user_campaigns = current_user.campaigns.order(created_at: :desc)
    unless user_campaigns.empty?
      render json: user_campaigns, each_serializer: Api::V1::UsersCampaignSerializer, status: :ok
    else
      handle_notfound
    end
  end

  def next
    campaign = Campaign.for_user current_user
    unless campaign.nil?
      render json: campaign, serializer: Api::V1::CampaignSerializer, status: :ok#, location: [:api, campaign]
    else
      handle_notfound
    end
  end

  def new
    render json: CampaignClass.active, each_serializer: Api::V1::CampaignClassSerializer, root: "campaign_classes", status: :ok
  end

  def create
    campaign_class = CampaignClass.active.find campaign_params[:campaign_class_id]
    creation = CreateCampaign.new(campaign_params, campaign_class, current_user)
    if creation.save
      head :created
    else
      render json: { errors: creation.campaign.errors }, status: :unprocessable_entity
    end
  end

=begin
  def show
    render json: Campaign.find(params[:id]), serializer: Api::V1::CampaignSerializer, status: :ok
  end
  def update
    campaign = current_user.campaigns.find params[:id]
    if campaign.update(campaign_params)
      render json: campaign, serializer: Api::V1::CampaignSerializer, status: :ok, location: [:api, campaign]
    else
      render json: { errors: campaign.errors }, status: :unprocessable_entity
    end
  end
=end
  private

  def campaign_params
    params.require(:campaign).permit(:campaign_class_id, :budget, :target_url, :description, :phone, :website, :address)
  end
end

app/controllers/managements/campaigns_controller.rb
class Managements::CampaignsController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :find_campaign, only: [:show, :update]

  def index
    @campaigns = Campaign.where.not(status: nil).order(created_at: :desc).page(params[:page])
  end

  def show
    @user_campaigns = @campaign.owner.campaigns.limit(5).order(created_at: :desc)
  end

  def update
    case params[:commit]
    when " پذیرش"
      @campaign.verify!
      @campaign.create_activity :verified, owner: current_manager
    when " درحال بررسی"
    when " غیرقابل قبول"
      @campaign.reject!
      @campaign.create_activity :rejected, owner: current_manager
    end
    redirect_to management_campaign_path(@campaign)
  end

  private

  def find_campaign
    @campaign = Campaign.find params[:id]
  end
end

app/controllers/managements/messages_controller.rb
class Managements::MessagesController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!

  def index
    @messages = Message.order(created_at: :desc).includes(:user).page(params[:page])
  end

  def show
    @message = Message.find params[:id]
    @message.read!
    @message.create_activity :read, owner: current_manager if @message.unread?
  end

  def destroy
  end
end

app/controllers/managements/product_types_controller.rb
class Managements::ProductTypesController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :all_product_types
  before_action :find_product_type, only: [:edit, :update, :destroy]

  def index
    reset_product_type
  end

  def create
    @product_type = ProductType.new(product_type_params)
    if @product_type.save
      @product_type.create_activity :created, owner: current_manager
      reset_product_type
    end
  end

  def edit
  end

  def update
    if @product_type.update_attributes(product_type_params)
      @product_type.create_activity :updated, owner: current_manager
      reset_product_type
    end
  end

  def destroy
    @product_type.create_activity :destroyed, owner: current_manager
    @product_type.destroy
  end

  private

  def product_type_params
    params.require(:product_type).permit(:name)
  end

  def all_product_types
    @product_types = ProductType.order(created_at: :asc).page(params[:page])
  end

  def find_product_type
    @product_type = ProductType.find(params[:id])
  end

  def reset_product_type
    @product_type = ProductType.new
  end
end

app/controllers/managements/products/product_details_controller.rb
class Managements::Products::ProductDetailsController < ApplicationController
  before_action :authenticate_manager!
  before_action :find_product_detail, only: [:edit, :update]

  def edit
  end

  def create
    @product = Product.find params[:product_id]
    @product_detail = @product.details.build(details_params)
    if @product_detail.save
      @product_detail.create_activity :created, owner: current_manager
      @product_detail = @product.details.build
    end
    all_product_details
  end

  def update
    @product = @product_detail.product
    if @product_detail.update_attributes(details_params)
      @product_detail.create_activity :updated, owner: current_manager
      @product_detail = @product.details.build
    end
    all_product_details
  end

  private

  def details_params
    params.require(:product_detail).permit(:code, :available).fix_numerals
  end

  def find_product_detail
    @product_detail = ProductDetail.find params[:id]
  end

  def all_product_details
    @product_details = @product.details.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/managements/products_controller.rb
class Managements::ProductsController < ApplicationController
  layout 'management'

  before_action :authenticate_manager!
  before_action :find_product, only: [:edit, :update, :show, :destroy]

  def index
    @products = Product.order(created_at: :desc).includes(:product_type).page(params[:page])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @product.create_activity :created, owner: current_manager
      redirect_to [:management, @product]
    else
      render 'new'
    end
  end

  def show
    @product_details = @product.details.order(created_at: :desc).includes(:product).page(params[:page])
    @product_detail = @product.details.build
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    if @product.update_attributes(product_params)
      @product.create_activity :updated, owner: current_manager
      redirect_to [:management, @product]
    else
      render 'edit'
    end
  end

  def destroy
    @product.create_activity :destroyed, owner: current_manager
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :description, :product_type_id, :available).fix_numerals
  end

  def find_product
    @product = Product.find params[:id]
  end
end

app/controllers/managements/reports_controller.rb
class Managements::ReportsController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :find_report, only: [:check, :uncheck, :destroy]

  def index
    @reports = Report.order(created_at: :desc).includes(:user, :campaign).page(params[:page])
  end

  def show
  end

  def check
    @report.check!
    @report.create_activity :checked, owner: current_manager
    redirect_to management_reports_path
  end

  def uncheck
    @report.uncheck!
    @report.create_activity :unchecked, owner: current_manager
    redirect_to management_reports_path
  end

  # def destroy
  #   @report.destroy
  #   redirect_to management_reports_path
  # end

  private

  def find_report
    @report = Report.find params[:id]
  end
end

app/controllers/managements/users_controller.rb
class Managements::UsersController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :get_user, only: [:show, :lock, :unlock]

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def show
  end

  def lock
    @user.lock_access!({ send_instructions: false })
    @user.create_activity :lock, owner: current_manager
  end

  def unlock
    @user.unlock_access!
    @user.create_activity :unlock, owner: current_manager
  end

  def update
  end

  private

  def get_user
    @user = User.find params[:id]
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!

  def show
    @activities = PublicActivity::Activity.order(created_at: :desc).limit(10).includes(:owner)
  end
end

app/views/managements/campaigns/index.html.erb
<div class="col-lg-12">
  <h1 class="text-primary" style=" font-size: 50px;"><span class="glyphicon glyphicon-heart" style="line-height: 30px;"></span> کمپین‌ها</h1>
</div>
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="row">
        <div class="col-sm-9 col-sm-push-3 col-xs-12">
          <div class="input-group" id="campaign-search">
            <input type="text" class="form-control" placeholder="" dir="ltr" style="font-family: 'Halvetica';">
            <span class="input-group-btn">
              <button class="btn btn-primary" type="button"><span class="glyphicon glyphicon-search" style="font-size: 12px; line-height: 8px;"></span></button>
            </span>
          </div>
        </div>
        <div class="col-sm-3 col-sm-pull-9 col-xs-3">
          <div class="dropdown" id="campaign-type-dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="campaignsdropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              آخرین کمپین‌ها
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="campaignsdropdown">
              <li><a href="#">آخرین کمپین‌ها</a></li>
              <li><a href="#">درحال نمایش</a></li>
              <li><a href="#">درانتظار تایید</a></li>
              <li><a href="#">تمام‌شده</a></li>
              <li><a href="#">رد شده</a></li>
            </ul>
          </div>
        </div>
        <div class="col-xs-12">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>شماره کمپین</th>
                <th>نوع کمپین</th>
                <th>نوع پرداخت</th>
                <th>ساخته‌شده در</th>
                <th >وضعیت</th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: 'shared/management/rows/campaign', collection: @campaigns %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="text-center">
            <%= paginate @campaigns %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-1">


    </div>

  </div>
</div>

app/views/managements/campaigns/show.html.erb
<div class="col-lg-12">
  <h1 class="text-primary" style=" font-size: 50px;"><span class="glyphicon glyphicon glyphicon-file" style="line-height: 30px;"></span> مشخصات‌کمپین</h1>
</div>
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-11 col-lg-offset-1">
      <div class="row">
        <div class="col-xs-6 col-lg-4 col-md-5">
          <div class="thumbnail">
            <%#= image_tag "2.jpeg", class: 'img-thumbnail img-responsive' %>
            <%= image_tag @campaign.cover.url(:medium), class: 'img-thumbnail img-responsive'%>
            <%= link_to "برو به سایت", @campaign.target_url, class: 'btn btn-lg btn-success', style: 'width: 100%;' %>
          </div>
        </div>
        <div class="col-xs-6 col-lg-8 col-md-7" id="campaign-details">
          <h4 style="font-size: 23px;"><span class="glyphicon glyphicon-user"></span> <%= link_to @campaign.owner.username, management_user_path(@campaign.owner) %></h4>
          <h4 style="font-size: 23px;"><span class="glyphicon glyphicon-time" style="line-height: 15px;"></span> <%= @campaign.created_at.to_parsi.strftime("%-d %B %Y در %k:%M:%S") %></h4>
          <h4 style="font-size: 23px;"><span class="glyphicon glyphicon-piggy-bank" style="line-height: 15px;"></span> <%= "#{@campaign.budget} #{t(@campaign.payment_type)}" %></h4>
          <h4 style="font-size: 23px;"><span class="glyphicon glyphicon-hourglass" style="line-height: 15px;"></span> <%= @campaign.waiting %> ثانیه</h4>
          <% flags = {"available" => "success", "ended" => "default",
                      "rejected" => "danger", "pending" => "info", "check_needed" => "warning"} %>
          <h4 style="font-size: 23px;"><span class="glyphicon glyphicon-info-sign" style="line-height: 15px;"></span><span class="text-<%= flags[@campaign.status] %>"> <%= t "campaign_status.#{@campaign.status}" %></span></h4>
          <h4 style="font-size: 23px;"><span class="glyphicon glyphicon-thumbs-up" style="line-height: 15px;"></span> <%= @campaign.total_likes %></h4>
        </div>

      </div>
    </div>
  </div>
</div>
<div class="col-lg-12">
  <div class="row">
    <div class="col-sm-5 col-lg-offset-1">
      <p><span style="font-size: 22px; line-height: 15px;" class="glyphicon glyphicon-align-right"></span> <%= @campaign.description %></p>
    </div>
    <div class="col-sm-6">
      <h3 style="margin-top: 0px;"><span class="glyphicon glyphicon-phone-alt"></span> <%= @campaign.phone %></h3>
      <h3 style="margin-top: 0px;" class="english"><span class="glyphicon glyphicon-link"></span> <%= link_to @campaign.website, @campaign.website %></h3>
      <h3 style="margin-top: 0px;"><span class="glyphicon glyphicon-map-marker"></span> <%= @campaign.address %></h3>
    </div>
  </div>
</div>
<div class="col-lg-12">
  <div class="row">
    <div class="col-sm-5 col-lg-offset-1">
      <div class="row">
        <div class="col-xs-12">
          <h3><span class="glyphicon glyphicon-stats"></span> پیشرفت کمپین</h3>
          <div class="progress">
            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;min-width: 2em;font-size: 18px;">
              60%
            </div>
          </div>
        </div>
        <div class="col-xs-12">
          <h3><span class="glyphicon glyphicon-cog"></span> تنظیمات</h3>
        </div>
        <div class="col-xs-10 col-xs-offset-1">


        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <h3><span class="glyphicon glyphicon-user"></span> درباره کاربر</h3>
      <h4 class="text-center">آخرین کمپین‌های کاربر</h4>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>شماره کمپین</th>
            <th>نوع کمپین</th>
            <th>نوع پرداخت</th>
            <th>ساخته‌شده در</th>
            <th >وضعیت</th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: 'shared/management/rows/campaign', collection: @user_campaigns %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="col-lg-12">
  <div class="row">
    <%= render partial: 'shared/management/controls/campaign', object: @campaign %>
  </div>
</div>