config/routes.rb
require 'api_constraints'
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :managers, :skip => [:sessions, :registrations, :unlocks]
  devise_scope :manager do
    get '/management/login' => 'devise/sessions#new', :as => :new_manager_session
    post '/management/login' => 'devise/sessions#create', :as => :manager_session
    delete 'management/logout' => 'devise/sessions#destroy', :as => :destroy_manager_session
  end

  resource :management, only: [:show] do
    authenticate :manager do
      mount Sidekiq::Web => '/sidekiq'
    end
    resources :users, only: [:index, :show, :update], controller: 'managements/users' do
      member do
        patch :lock
        patch :unlock
      end
    end
    resources :campaigns, only: [:index, :show, :update], controller: 'managements/campaigns'
    resources :reports, only: [:index], controller: 'managements/reports' do
      member do
        patch :check
        patch :uncheck
      end
    end
    resources :messages, only: [:index, :show, :destroy], controller: 'managements/messages'
    resources :product_types, only: [:index, :new, :create, :edit, :update, :destroy], controller: 'managements/product_types'
    resources :products, controller: 'managements/products' do
      resources :product_details, controller: 'managements/products/product_details', only: [:create, :edit, :update]
    end
  end
#============================ Dashboard ROUTES =======================#
  resource :dashboard, only: [:show] do
    resources :bundles, only: [:index], controller: 'dashboards/bundles' do
      resource :purchase, only: [:create, :show], controller: 'dashboards/bundles/purchases' do
        member do
          get :callback
        end
      end
    end
  end
#============================ USERS ROUTES ============================#
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :passwords, :registrations]
  devise_scope :user do
    get "/login" => "sessions#new", :as => :new_user_session
  end
  resource :session, only: [:show]
#============================ API ROUTES ===============================#
  namespace :api, defaults: { format: :json } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, only: [:index] do
        collection do
          get :self
        end
      end
      resources :sessions, only: [:create]
      resources :campaigns, only: [:index, :new, :create] do
        resource :like, only: [:create], controller: 'campaigns/likes'
        resource :report, only: [:create], controller: 'campaigns/reports'
        collection do
          get :next
        end
      end
      resources :products, only: [:index] do
        resource :purchase, only: [:create], controller: 'products/purchases'
      end
      resources :bundles, only: [:index]
      post 'bundles/:bazaar_sku/purchase' => 'bundles/purchases#create', as: :bundle_purchase
      resources :messages, only: [:create]
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :product_type
  has_many :details, class_name: 'ProductDetail', dependent: :destroy
  has_many :buyers, through: :details, source: :user

  validates :title, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :product_type_id, presence: true # Cannot be :product_type, it messes with client_side_validation.

  accepts_nested_attributes_for :details

  scope :available, -> { where available: true }
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  include PublicActivity::Common
  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/api/v1/products/purchases_controller.rb
class Api::V1::Products::PurchasesController < Api::V1::ApiController

  def create
    product = Product.available.find params[:product_id]
    purchase = PurchaseProduct.new(current_user, product)
    if purchase.buy
      render json: purchase.purchased_detail, serializer: Api::V1::DetailSerializer, root: 'detail', status: :created
    else
      render json: { errors: purchase.user.errors }, status: :unprocessable_entity
    end
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::ApiController
  def index
    products = Product.available.all.includes(:product_type)
    unless products.empty?
      render json: products, each_serializer: Api::V1::ProductSerializer, status: :ok
    else
      handle_notfound
    end
  end
end

app/controllers/managements/campaigns_controller.rb
class Managements::CampaignsController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :find_campaign, only: [:show, :update]

  def index
    @campaigns = Campaign.where.not(status: nil).order(created_at: :desc).page(params[:page])
  end

  def show
    @user_campaigns = @campaign.owner.campaigns.limit(5).order(created_at: :desc)
  end

  def update
    case params[:commit]
    when " پذیرش"
      @campaign.verify!
      @campaign.create_activity :verified, owner: current_manager
    when " درحال بررسی"
    when " غیرقابل قبول"
      @campaign.reject!
      @campaign.create_activity :rejected, owner: current_manager
    end
    redirect_to management_campaign_path(@campaign)
  end

  private

  def find_campaign
    @campaign = Campaign.find params[:id]
  end
end

app/controllers/managements/messages_controller.rb
class Managements::MessagesController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!

  def index
    @messages = Message.order(created_at: :desc).includes(:user).page(params[:page])
  end

  def show
    @message = Message.find params[:id]
    @message.read!
    @message.create_activity :read, owner: current_manager if @message.unread?
  end

  def destroy
  end
end

app/controllers/managements/product_types_controller.rb
class Managements::ProductTypesController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :all_product_types
  before_action :find_product_type, only: [:edit, :update, :destroy]

  def index
    reset_product_type
  end

  def create
    @product_type = ProductType.new(product_type_params)
    if @product_type.save
      @product_type.create_activity :created, owner: current_manager
      reset_product_type
    end
  end

  def edit
  end

  def update
    if @product_type.update_attributes(product_type_params)
      @product_type.create_activity :updated, owner: current_manager
      reset_product_type
    end
  end

  def destroy
    @product_type.create_activity :destroyed, owner: current_manager
    @product_type.destroy
  end

  private

  def product_type_params
    params.require(:product_type).permit(:name)
  end

  def all_product_types
    @product_types = ProductType.order(created_at: :asc).page(params[:page])
  end

  def find_product_type
    @product_type = ProductType.find(params[:id])
  end

  def reset_product_type
    @product_type = ProductType.new
  end
end

app/controllers/managements/products/product_details_controller.rb
class Managements::Products::ProductDetailsController < ApplicationController
  before_action :authenticate_manager!
  before_action :find_product_detail, only: [:edit, :update]

  def edit
  end

  def create
    @product = Product.find params[:product_id]
    @product_detail = @product.details.build(details_params)
    if @product_detail.save
      @product_detail.create_activity :created, owner: current_manager
      @product_detail = @product.details.build
    end
    all_product_details
  end

  def update
    @product = @product_detail.product
    if @product_detail.update_attributes(details_params)
      @product_detail.create_activity :updated, owner: current_manager
      @product_detail = @product.details.build
    end
    all_product_details
  end

  private

  def details_params
    params.require(:product_detail).permit(:code, :available).fix_numerals
  end

  def find_product_detail
    @product_detail = ProductDetail.find params[:id]
  end

  def all_product_details
    @product_details = @product.details.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/managements/products_controller.rb
class Managements::ProductsController < ApplicationController
  layout 'management'

  before_action :authenticate_manager!
  before_action :find_product, only: [:edit, :update, :show, :destroy]

  def index
    @products = Product.order(created_at: :desc).includes(:product_type).page(params[:page])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @product.create_activity :created, owner: current_manager
      redirect_to [:management, @product]
    else
      render 'new'
    end
  end

  def show
    @product_details = @product.details.order(created_at: :desc).includes(:product).page(params[:page])
    @product_detail = @product.details.build
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    if @product.update_attributes(product_params)
      @product.create_activity :updated, owner: current_manager
      redirect_to [:management, @product]
    else
      render 'edit'
    end
  end

  def destroy
    @product.create_activity :destroyed, owner: current_manager
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :description, :product_type_id, :available).fix_numerals
  end

  def find_product
    @product = Product.find params[:id]
  end
end

app/controllers/managements/reports_controller.rb
class Managements::ReportsController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :find_report, only: [:check, :uncheck, :destroy]

  def index
    @reports = Report.order(created_at: :desc).includes(:user, :campaign).page(params[:page])
  end

  def show
  end

  def check
    @report.check!
    @report.create_activity :checked, owner: current_manager
    redirect_to management_reports_path
  end

  def uncheck
    @report.uncheck!
    @report.create_activity :unchecked, owner: current_manager
    redirect_to management_reports_path
  end

  # def destroy
  #   @report.destroy
  #   redirect_to management_reports_path
  # end

  private

  def find_report
    @report = Report.find params[:id]
  end
end

app/controllers/managements/users_controller.rb
class Managements::UsersController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!
  before_action :get_user, only: [:show, :lock, :unlock]

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def show
  end

  def lock
    @user.lock_access!({ send_instructions: false })
    @user.create_activity :lock, owner: current_manager
  end

  def unlock
    @user.unlock_access!
    @user.create_activity :unlock, owner: current_manager
  end

  def update
  end

  private

  def get_user
    @user = User.find params[:id]
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  layout 'management'
  before_action :authenticate_manager!

  def show
    @activities = PublicActivity::Activity.order(created_at: :desc).limit(10).includes(:owner)
  end
end

app/views/managements/products/create.html.erb
<h1>Managements::Products#create</h1>
<p>Find me in app/views/managements/products/create.html.erb</p>

app/views/managements/products/destroy.html.erb
<h1>Managements::Products#destroy</h1>
<p>Find me in app/views/managements/products/destroy.html.erb</p>

app/views/managements/products/edit.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-11">
      <h1 class="text-primary" style="font-size: 50px;"><span class="glyphicon glyphicon glyphicon-file" style="line-height: 30px;"></span> ویرایش‌محصول</h1>
    </div>
    <div class="col-xs-2 col-sm-2 col-md-1">
      <%= link_to management_product_path(@product) do %>
        <h1 class="text-primary" style="font-size: 50px;"><span class="glyphicon glyphicon-menu-left"></span></h1>
      <% end %>
    </div>
  </div>
</div>
<div class="col-lg-12">
  <div class="row">
    <%= render partial: 'shared/management/forms/product', object: @product %>
  </div>
</div>
<div class="col-lg-12">
  <div class="row">

  </div>
</div>

app/views/managements/products/index.html.erb
<div class="col-lg-12">
  <h1 class="text-primary" style=" font-size: 50px;"><span class="glyphicon glyphicon-shopping-cart" style="line-height: 30px;"></span> فروشگاه</h1>
</div>
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-3 col-lg-offset-1 col-md-4 col-xs-5" style="padding-bottom: 10px;">
      <%= link_to "محصول جدید", new_management_product_path, class: "btn btn-lg btn-primary", style: "width: 100%;" %>
    </div>
    <div class="col-lg-3 col-lg-offset-4 col-md-4 col-md-offset-4 col-xs-5 col-xs-offset-2" style="padding-bottom: 10px;">
      <%= link_to "مدیریت دسته‌ها", management_product_types_path, class: "btn btn-lg btn-primary", style: "width: 100%;" %>
    </div>
  </div>
</div>
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="row">
        <div class="col-sm-9 col-sm-push-3 col-xs-12">
          <div class="input-group" id="campaign-search">
            <input type="text" class="form-control" placeholder="جستجوی محصولات" dir="rtl">
            <span class="input-group-btn">
              <button class="btn btn-primary" type="button"><span class="glyphicon glyphicon-search" style="font-size: 12px; line-height: 8px;"></span></button>
            </span>
          </div>
        </div>
        <div class="col-sm-3 col-sm-pull-9 col-xs-3">
          <div class="dropdown" id="campaign-type-dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="campaignsdropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              همه محصولات
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="campaignsdropdown">
              <li><a href="#">همه محصولات</a></li>
              <li><a href="#">محصولات موجود</a></li>
              <li><a href="#">محصولات ناموجود</a></li>
            </ul>
          </div>
        </div>
        <div class="col-xs-12">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>شماره محصول</th>
                <th>نام</th>
                <th>دسته</th>
                <th>قیمت (سکه)</th>
                <th>وضعیت</th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: 'shared/management/rows/product', collection: @products %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="text-center">
            <%= paginate @products %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-1">


    </div>

  </div>
</div>

app/views/managements/products/new.html.erb
<div class="col-lg-12">
  <h1 class="text-primary" style=" font-size: 50px;"><span class="glyphicon glyphicon glyphicon-file" style="line-height: 30px;"></span> محصول جدید</h1>
</div>
<div class="col-lg-12">
  <div class="row">
    <%= render partial: 'shared/management/forms/product', object: @product %>
  </div>
</div>
<div class="col-lg-12">
  <div class="row">

  </div>
</div>

app/views/managements/products/show.html.erb
<div class="col-lg-12">
  <h1 class="text-primary" style=" font-size: 50px;"><span class="glyphicon glyphicon glyphicon-file" style="line-height: 30px;"></span> مشخصات‌محصول</h1>
</div>
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-11 col-lg-offset-1">
      <div class="row">
        <div class="col-lg-12">
          <h2><span class="glyphicon glyphicon-tag" style="line-height: 20px;"></span> <%= @product.title %> <%= link_to "ویرایش", edit_management_product_path(@product), class: "btn-sm btn-primary" %></h2>
        </div>
        <div class="col-sm-8">
          <p><span class="glyphicon glyphicon-align-right" style="font-size: 22px;line-height: 15px;"></span> <%= @product.description %></p>
        </div>
        <div class="col-sm-4">
          <h3><span class="glyphicon glyphicon-certificate" style="line-height: 15px;"></span> <%= t @product.product_type.name %></h3>
          <h3><span class="glyphicon glyphicon-tag" style="line-height: 15px;"></span> <%= @product.price %> سکه</h3>
          <h3><span class="glyphicon glyphicon-info-sign" style="line-height: 15px;"></span> <%= @product.available ? "موجود" : "ناموجود" %></h3>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <div class="row" id="detail-form">
        <%= render(partial: "shared/management/forms/product_detail", object: @product_detail) %>
      </div>
      <div class="row">
        <table class="table table-hover">
          <thead>
            <th>شماره‌آیتم</th>
            <th>کد</th>
            <th>وضعیت</th>
            <th>خریدار</th>
            <th>تنظیمات</th>
          </thead>
          <tbody id="table-body">
            <%= render partial: "shared/management/rows/product_detail", collection: @product_details %>
          </tbody>
        </table>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="text-center" id="pagination">
            <%= paginate @product_details %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>